# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170401_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbinfo',
            name='lable',
            field=models.CharField(default='lable', max_length=250),
        ),
        migrations.AddField(
            model_name='cmdbinfo',
            name='password',
            field=models.CharField(default='password', max_length=250),
        ),
        migrations.AlterField(
            model_name='cmdbinfo',
            name='hostname',
            field=models.CharField(default='hostname', max_length=250),
        ),
        migrations.AlterField(
            model_name='cmdbinfo',
            name='ip',
            field=models.CharField(default='192.168.0.1', max_length=250),
        ),
    ]
