# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170405_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbinfo',
            name='area',
            field=models.CharField(default='area', max_length=250),
        ),
    ]
