# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170413_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbinfo',
            name='ip',
            field=models.CharField(default='192.168.0.1', max_length=250),
        ),
    ]
