# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
