# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_uploadfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
