# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170413_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbinfo',
            name='os',
            field=models.CharField(default='os', max_length=250),
        ),
    ]
