# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170428_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbinfo',
            name='hostname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cmdbinfo',
            name='lable',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cmdbinfo',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
